INSERT INTO Item (name, price, description, category, image_path) VALUES ('Martingale Collar', 25.00, 'Training collar for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Prong Collar', 21.00, 'Training collar for aggressive pulling dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Standard Dog Leash', 12.00, 'Standard leash for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Retractable Leash', 8.00, 'Retractable leash for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Slip lead', 2.00, 'Collar/leash in one for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cage Muzzle', 10.00, 'Muzzle for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Strap Muzzle', 8.00, 'Muzzle for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Dog Harness', 30.00, 'Harness for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Working Dog Backpack', 60.00, 'Backpack for working dog breeds.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cold Weather Boots', 55.00, 'Boots for dogs to protect against the cold.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Hot Weather Boots', 55.00, 'Boots for dogs to protect against the hot.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Poop Bags', 5.00, 'Bags for picking up dog poop.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Paw Pad Balm', 12.00, 'Balm for dry/cracked dog paw pads.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Nose Balm', 12.00, 'Balm for dry/cracked dog noses.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Poop Bag Holder', 3.00, 'Holder for dog poop bags.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Nail Trimmer(Dogs)', 8.00, 'Nail Trimmer for dogs.', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Dog Food', 60.00, 'Food for dogs', 'Dog', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Quick Release Collar', 3.00, 'Quick Release Collar for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Nail Caps', 2.00, 'Nail caps for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Carrier', 25.00, 'Handheld Kennel for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Collar Charm', 8.00, 'Charm for cat collars.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Nail Clippers(Cats)', 8.00, 'Cat nail clippers.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Hair Ball Relief Treats', 12.00, 'Treats to help relieve hair balls.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Litter Box', 10.00, 'Litter Box for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Litter', 25.00, 'Litter for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Nip', 6.00, 'Cat nip.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Scratching Post', 40.00, 'Scratching post for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Tree', 60.00, 'Cat tree.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Treats', 10.00, 'Treats for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Slicker Brush', 12.00, 'Brush for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Litter Mat', 12.00, 'Mat for litter boxes.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Mouse Toy', 1.00, 'Mouse toy for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Pole Toy', 1.50, 'Pole toy for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Bed', 25.00, 'Bed for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cat Food', 20.00, 'Food for cats.', 'Cat', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Bird Cage', 35.00, 'Cage for a bird.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Hamster Cage', 70.00, 'Cage for a hamster.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Rabbit Cage', 70.00, 'Cage for a rabbit.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Guinea Pig Cage', 70.00, 'Cage for a guinea pig.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Hamster Wheel', 20.00, 'Wheel for hamsters.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Cage Bedding', 25.00, 'Bedding for small animal cages.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Water Bottle', 4.00, 'Water Bottle for small animal cages.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Food Bowl', 1.00, 'Food Bowl for small animals', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Ferret Sling', 12.00, 'Sling/hammock for ferrets.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Sugar Glider Canopy', 18.00, 'Canopy for Sugar Gliders.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Small Animal Igloo', 2.00, 'Igloo shaped house for small animals.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Timothy Hay', 12.00, 'Food for small rodents.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Alfalfa Hay', 12.00, 'Food for small rodents.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Yogurt Drops', 5.00, 'Probiotic treats for small animals.', 'Small Animal', 'placeholder');
INSERT INTO Item (name, price, description, category, image_path) VALUES ('Hamster Tunnel', 80.00, 'Tunnel for hamsters.', 'Small Animal', 'placeholder');